"""Phase 3/4 auth backend: reports carry user_id when generated by a signed-in
user, GET /reports scopes to the caller + public samples, and every report
endpoint rejects anonymous access (Phase 4 login wall).

    python -m pytest backend/tests/test_reports_scoping.py
"""
import os
import sys
import time
import uuid

import pytest
import requests

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from agents.auth import COOKIE_NAME

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "http://localhost:8001").rstrip("/")
API = f"{BASE_URL}/api"


def _register() -> dict:
    creds = {"email": f"scopetest+{uuid.uuid4().hex[:12]}@example.com", "password": "correct-horse-battery"}
    r = requests.post(f"{API}/auth/register", json=creds)
    assert r.status_code == 200, r.text
    token = r.cookies.get(COOKIE_NAME)
    assert token
    return {COOKIE_NAME: token}


@pytest.fixture(scope="module")
def user_cookie():
    return _register()


@pytest.fixture(scope="module")
def other_user_cookie():
    return _register()


def _generate_and_wait(cookies: dict) -> str:
    r = requests.post(f"{API}/reports/generate",
                       json={"ticker": "AAPL", "query": "Summarize the latest quarter", "no_cache": True},
                       cookies=cookies)
    assert r.status_code == 200, r.text
    job_id = r.json()["job_id"]
    start = time.time()
    while time.time() - start < 300:
        r = requests.get(f"{API}/reports/{job_id}", cookies=cookies)
        status = r.json().get("status")
        if status == "completed":
            return job_id
        assert status not in ("failed", "cancelled"), r.text
        time.sleep(2)
    raise TimeoutError(f"report {job_id} did not complete in time")


@pytest.fixture(scope="module")
def authed_job_id(user_cookie):
    return _generate_and_wait(user_cookie)


def test_report_tagged_with_user_id(user_cookie, authed_job_id):
    r = requests.get(f"{API}/reports/{authed_job_id}", cookies=user_cookie)
    assert r.json()["report"]["user_id"] is not None


# ---------- Phase 4 login wall: anonymous access is rejected ----------

def test_anonymous_generate_rejected():
    r = requests.post(f"{API}/reports/generate", json={"ticker": "AAPL", "query": "hi"})
    assert r.status_code == 401


def test_anonymous_list_rejected():
    r = requests.get(f"{API}/reports")
    assert r.status_code == 401


def test_anonymous_get_report_rejected(authed_job_id):
    r = requests.get(f"{API}/reports/{authed_job_id}")
    assert r.status_code == 401


def test_anonymous_stream_rejected(authed_job_id):
    r = requests.get(f"{API}/reports/{authed_job_id}/stream")
    assert r.status_code == 401


def test_anonymous_delete_rejected(authed_job_id):
    r = requests.delete(f"{API}/reports/{authed_job_id}")
    assert r.status_code == 401


def test_anonymous_compare_rejected(authed_job_id):
    r = requests.post(f"{API}/reports/compare", json={"report_ids": [authed_job_id, authed_job_id]})
    assert r.status_code == 401


def test_anonymous_rescore_rejected():
    r = requests.post(f"{API}/reports/rescore")
    assert r.status_code == 401


# ---------- Per-user isolation ----------

def test_list_scopes_to_caller(user_cookie, authed_job_id):
    r = requests.get(f"{API}/reports", cookies=user_cookie)
    assert r.status_code == 200, r.text
    ids = [x["id"] for x in r.json()["reports"]]
    assert authed_job_id in ids


def test_other_user_does_not_see_my_report(other_user_cookie, authed_job_id):
    """A second, unrelated signed-in user must not see the first user's
    private report in their listing — the core privacy guarantee of the
    Phase 4 cutover (previously any caller saw every report)."""
    r = requests.get(f"{API}/reports", params={"limit": 500}, cookies=other_user_cookie)
    assert r.status_code == 200, r.text
    ids = [x["id"] for x in r.json()["reports"]]
    assert authed_job_id not in ids


def test_samples_visible_to_any_authed_user(other_user_cookie):
    """Phase 3 migration curated MSFT+AAPL as public samples; confirm they
    still list for a user who never generated a report themself. Samples are
    the oldest reports in the collection, so a large limit is needed."""
    r = requests.get(f"{API}/reports", params={"limit": 500}, cookies=other_user_cookie)
    assert r.status_code == 200
    samples = [x for x in r.json()["reports"] if x.get("is_sample")]
    assert len(samples) >= 2


# ---------- Delete is scoped to the owner (found in Phase 4 review: an
# unscoped delete let any signed-in user wipe another user's report, or the
# shared public samples since their ids are visible to every caller) ----------

def test_other_user_cannot_delete_my_report(user_cookie, other_user_cookie, authed_job_id):
    r = requests.delete(f"{API}/reports/{authed_job_id}", cookies=other_user_cookie)
    assert r.status_code == 404
    # still there for the owner
    r = requests.get(f"{API}/reports/{authed_job_id}", cookies=user_cookie)
    assert r.status_code == 200


def test_cannot_delete_sample():
    """Samples have user_id=None — no signed-in user's id ever matches, so
    the ownership-scoped delete makes them effectively read-only."""
    cookies = _register()
    r = requests.get(f"{API}/reports", params={"limit": 500}, cookies=cookies)
    sample = next(x for x in r.json()["reports"] if x.get("is_sample"))
    d = requests.delete(f"{API}/reports/{sample['id']}", cookies=cookies)
    assert d.status_code == 404
    # confirm it's still there
    g = requests.get(f"{API}/reports/{sample['id']}", cookies=cookies)
    assert g.status_code == 200
