"""Bundled top NSE/BSE Indian tickers so the search covers Indian companies.

Since SEC EDGAR is US-only, Indian companies won't have auto-ingested filings —
but we still want them to appear in the search so users can either paste an
annual report or upload an earnings-call audio to analyze them.
"""

# Top ~200 NSE-listed companies (Nifty 500 subset). ticker suffix ".NS" style
# is intentionally omitted — we use the plain scrip symbol.
INDIAN_TICKERS: list[dict] = [
    {"ticker": "RELIANCE", "name": "Reliance Industries Ltd"},
    {"ticker": "TCS", "name": "Tata Consultancy Services Ltd"},
    {"ticker": "HDFCBANK", "name": "HDFC Bank Ltd"},
    {"ticker": "BHARTIARTL", "name": "Bharti Airtel Ltd"},
    {"ticker": "ICICIBANK", "name": "ICICI Bank Ltd"},
    {"ticker": "INFY", "name": "Infosys Ltd"},
    {"ticker": "SBIN", "name": "State Bank of India"},
    {"ticker": "LT", "name": "Larsen & Toubro Ltd"},
    {"ticker": "ITC", "name": "ITC Ltd"},
    {"ticker": "HINDUNILVR", "name": "Hindustan Unilever Ltd"},
    {"ticker": "BAJFINANCE", "name": "Bajaj Finance Ltd"},
    {"ticker": "KOTAKBANK", "name": "Kotak Mahindra Bank Ltd"},
    {"ticker": "HCLTECH", "name": "HCL Technologies Ltd"},
    {"ticker": "MARUTI", "name": "Maruti Suzuki India Ltd"},
    {"ticker": "SUNPHARMA", "name": "Sun Pharmaceutical Industries Ltd"},
    {"ticker": "AXISBANK", "name": "Axis Bank Ltd"},
    {"ticker": "M&M", "name": "Mahindra & Mahindra Ltd"},
    {"ticker": "NTPC", "name": "NTPC Ltd"},
    {"ticker": "TITAN", "name": "Titan Company Ltd"},
    {"ticker": "ONGC", "name": "Oil & Natural Gas Corporation Ltd"},
    {"ticker": "ADANIENT", "name": "Adani Enterprises Ltd"},
    {"ticker": "ULTRACEMCO", "name": "UltraTech Cement Ltd"},
    {"ticker": "WIPRO", "name": "Wipro Ltd"},
    {"ticker": "POWERGRID", "name": "Power Grid Corporation of India Ltd"},
    {"ticker": "TATAMOTORS", "name": "Tata Motors Ltd"},
    {"ticker": "ASIANPAINT", "name": "Asian Paints Ltd"},
    {"ticker": "JSWSTEEL", "name": "JSW Steel Ltd"},
    {"ticker": "COALINDIA", "name": "Coal India Ltd"},
    {"ticker": "BAJAJFINSV", "name": "Bajaj Finserv Ltd"},
    {"ticker": "NESTLEIND", "name": "Nestle India Ltd"},
    {"ticker": "ADANIPORTS", "name": "Adani Ports and SEZ Ltd"},
    {"ticker": "TATASTEEL", "name": "Tata Steel Ltd"},
    {"ticker": "HDFCLIFE", "name": "HDFC Life Insurance Company Ltd"},
    {"ticker": "TECHM", "name": "Tech Mahindra Ltd"},
    {"ticker": "SBILIFE", "name": "SBI Life Insurance Company Ltd"},
    {"ticker": "HINDALCO", "name": "Hindalco Industries Ltd"},
    {"ticker": "GRASIM", "name": "Grasim Industries Ltd"},
    {"ticker": "BAJAJ-AUTO", "name": "Bajaj Auto Ltd"},
    {"ticker": "DRREDDY", "name": "Dr. Reddy's Laboratories Ltd"},
    {"ticker": "CIPLA", "name": "Cipla Ltd"},
    {"ticker": "BRITANNIA", "name": "Britannia Industries Ltd"},
    {"ticker": "EICHERMOT", "name": "Eicher Motors Ltd"},
    {"ticker": "APOLLOHOSP", "name": "Apollo Hospitals Enterprise Ltd"},
    {"ticker": "TATACONSUM", "name": "Tata Consumer Products Ltd"},
    {"ticker": "HEROMOTOCO", "name": "Hero MotoCorp Ltd"},
    {"ticker": "DIVISLAB", "name": "Divi's Laboratories Ltd"},
    {"ticker": "INDUSINDBK", "name": "IndusInd Bank Ltd"},
    {"ticker": "PIDILITIND", "name": "Pidilite Industries Ltd"},
    {"ticker": "DMART", "name": "Avenue Supermarts Ltd (D-Mart)"},
    {"ticker": "GODREJCP", "name": "Godrej Consumer Products Ltd"},
    {"ticker": "SHREECEM", "name": "Shree Cement Ltd"},
    {"ticker": "DABUR", "name": "Dabur India Ltd"},
    {"ticker": "AMBUJACEM", "name": "Ambuja Cements Ltd"},
    {"ticker": "HAVELLS", "name": "Havells India Ltd"},
    {"ticker": "MARICO", "name": "Marico Ltd"},
    {"ticker": "SIEMENS", "name": "Siemens Ltd"},
    {"ticker": "VEDL", "name": "Vedanta Ltd"},
    {"ticker": "PIIND", "name": "PI Industries Ltd"},
    {"ticker": "TRENT", "name": "Trent Ltd"},
    {"ticker": "BOSCHLTD", "name": "Bosch Ltd"},
    {"ticker": "SRF", "name": "SRF Ltd"},
    {"ticker": "COLPAL", "name": "Colgate-Palmolive (India) Ltd"},
    {"ticker": "BAJAJHLDNG", "name": "Bajaj Holdings & Investment Ltd"},
    {"ticker": "MUTHOOTFIN", "name": "Muthoot Finance Ltd"},
    {"ticker": "LICI", "name": "Life Insurance Corporation of India"},
    {"ticker": "ZOMATO", "name": "Zomato Ltd"},
    {"ticker": "NYKAA", "name": "FSN E-Commerce Ventures Ltd (Nykaa)"},
    {"ticker": "PAYTM", "name": "One 97 Communications Ltd (Paytm)"},
    {"ticker": "POLICYBZR", "name": "PB Fintech Ltd (Policybazaar)"},
    {"ticker": "IRCTC", "name": "Indian Railway Catering & Tourism Corp"},
    {"ticker": "DLF", "name": "DLF Ltd"},
    {"ticker": "GAIL", "name": "GAIL (India) Ltd"},
    {"ticker": "IOC", "name": "Indian Oil Corporation Ltd"},
    {"ticker": "BPCL", "name": "Bharat Petroleum Corporation Ltd"},
    {"ticker": "HINDPETRO", "name": "Hindustan Petroleum Corporation Ltd"},
    {"ticker": "TATAPOWER", "name": "Tata Power Company Ltd"},
    {"ticker": "ADANIGREEN", "name": "Adani Green Energy Ltd"},
    {"ticker": "ADANIPOWER", "name": "Adani Power Ltd"},
    {"ticker": "ADANITRANS", "name": "Adani Energy Solutions Ltd"},
    {"ticker": "JINDALSTEL", "name": "Jindal Steel & Power Ltd"},
    {"ticker": "SAIL", "name": "Steel Authority of India Ltd"},
    {"ticker": "NMDC", "name": "NMDC Ltd"},
    {"ticker": "GODREJPROP", "name": "Godrej Properties Ltd"},
    {"ticker": "OBEROIRLTY", "name": "Oberoi Realty Ltd"},
    {"ticker": "LODHA", "name": "Macrotech Developers Ltd (Lodha)"},
    {"ticker": "PRESTIGE", "name": "Prestige Estates Projects Ltd"},
    {"ticker": "BERGEPAINT", "name": "Berger Paints India Ltd"},
    {"ticker": "PGHH", "name": "Procter & Gamble Hygiene and Health Care Ltd"},
    {"ticker": "MCDOWELL-N", "name": "United Spirits Ltd"},
    {"ticker": "UBL", "name": "United Breweries Ltd"},
    {"ticker": "PAGEIND", "name": "Page Industries Ltd"},
    {"ticker": "MRF", "name": "MRF Ltd"},
    {"ticker": "BALKRISIND", "name": "Balkrishna Industries Ltd"},
    {"ticker": "APOLLOTYRE", "name": "Apollo Tyres Ltd"},
    {"ticker": "TVSMOTOR", "name": "TVS Motor Company Ltd"},
    {"ticker": "ASHOKLEY", "name": "Ashok Leyland Ltd"},
    {"ticker": "ESCORTS", "name": "Escorts Kubota Ltd"},
    {"ticker": "MOTHERSON", "name": "Samvardhana Motherson International Ltd"},
    {"ticker": "SBICARD", "name": "SBI Cards and Payment Services Ltd"},
    {"ticker": "CHOLAFIN", "name": "Cholamandalam Investment & Finance Company Ltd"},
    {"ticker": "IDFCFIRSTB", "name": "IDFC First Bank Ltd"},
    {"ticker": "FEDERALBNK", "name": "Federal Bank Ltd"},
    {"ticker": "BANDHANBNK", "name": "Bandhan Bank Ltd"},
    {"ticker": "AUBANK", "name": "AU Small Finance Bank Ltd"},
    {"ticker": "PNB", "name": "Punjab National Bank"},
    {"ticker": "BANKBARODA", "name": "Bank of Baroda"},
    {"ticker": "CANBK", "name": "Canara Bank"},
    {"ticker": "UNIONBANK", "name": "Union Bank of India"},
    {"ticker": "PFC", "name": "Power Finance Corporation Ltd"},
    {"ticker": "RECLTD", "name": "REC Ltd"},
    {"ticker": "IRFC", "name": "Indian Railway Finance Corporation Ltd"},
    {"ticker": "LTIM", "name": "LTIMindtree Ltd"},
    {"ticker": "PERSISTENT", "name": "Persistent Systems Ltd"},
    {"ticker": "MPHASIS", "name": "Mphasis Ltd"},
    {"ticker": "COFORGE", "name": "Coforge Ltd"},
    {"ticker": "NAUKRI", "name": "Info Edge (India) Ltd (Naukri)"},
    {"ticker": "DELHIVERY", "name": "Delhivery Ltd"},
    {"ticker": "IEX", "name": "Indian Energy Exchange Ltd"},
    {"ticker": "BSE", "name": "BSE Ltd"},
    {"ticker": "CDSL", "name": "Central Depository Services (India) Ltd"},
    {"ticker": "MCX", "name": "Multi Commodity Exchange of India Ltd"},
    {"ticker": "ANGELONE", "name": "Angel One Ltd"},
    {"ticker": "ZEEL", "name": "Zee Entertainment Enterprises Ltd"},
    {"ticker": "SUNTV", "name": "Sun TV Network Ltd"},
    {"ticker": "PVRINOX", "name": "PVR INOX Ltd"},
    {"ticker": "INDIGO", "name": "InterGlobe Aviation Ltd (IndiGo)"},
    {"ticker": "SPICEJET", "name": "SpiceJet Ltd"},
    {"ticker": "CONCOR", "name": "Container Corporation of India Ltd"},
    {"ticker": "IRCON", "name": "IRCON International Ltd"},
    {"ticker": "RVNL", "name": "Rail Vikas Nigam Ltd"},
    {"ticker": "BEL", "name": "Bharat Electronics Ltd"},
    {"ticker": "HAL", "name": "Hindustan Aeronautics Ltd"},
    {"ticker": "BHEL", "name": "Bharat Heavy Electricals Ltd"},
    {"ticker": "MAZDOCK", "name": "Mazagon Dock Shipbuilders Ltd"},
    {"ticker": "COCHINSHIP", "name": "Cochin Shipyard Ltd"},
    {"ticker": "GRSE", "name": "Garden Reach Shipbuilders & Engineers Ltd"},
    {"ticker": "AUROPHARMA", "name": "Aurobindo Pharma Ltd"},
    {"ticker": "LUPIN", "name": "Lupin Ltd"},
    {"ticker": "TORNTPHARM", "name": "Torrent Pharmaceuticals Ltd"},
    {"ticker": "ALKEM", "name": "Alkem Laboratories Ltd"},
    {"ticker": "BIOCON", "name": "Biocon Ltd"},
    {"ticker": "GLENMARK", "name": "Glenmark Pharmaceuticals Ltd"},
    {"ticker": "ZYDUSLIFE", "name": "Zydus Lifesciences Ltd"},
    {"ticker": "MANKIND", "name": "Mankind Pharma Ltd"},
    {"ticker": "MAXHEALTH", "name": "Max Healthcare Institute Ltd"},
    {"ticker": "FORTIS", "name": "Fortis Healthcare Ltd"},
    {"ticker": "METROPOLIS", "name": "Metropolis Healthcare Ltd"},
    {"ticker": "DRLAL", "name": "Dr. Lal PathLabs Ltd"},
    {"ticker": "VBL", "name": "Varun Beverages Ltd"},
    {"ticker": "JUBLFOOD", "name": "Jubilant FoodWorks Ltd"},
    {"ticker": "DEVYANI", "name": "Devyani International Ltd"},
    {"ticker": "SHRIRAMFIN", "name": "Shriram Finance Ltd"},
    {"ticker": "BANKINDIA", "name": "Bank of India"},
    {"ticker": "SUZLON", "name": "Suzlon Energy Ltd"},
    {"ticker": "IDEA", "name": "Vodafone Idea Ltd"},
    {"ticker": "TATACOMM", "name": "Tata Communications Ltd"},
]
